fastlane_version "1.98.0"

default_platform :ios

platform :ios do
  before_all do |lane, options|
    return if lane_context[SharedValues::LANE_NAME] == 'ios register'
    
    sh "cd .. && scripts/carthage.sh"
    cocoapods(use_bundle_exec: true)
    match(readonly: true)
    increment_version_number(version_number: number_of_commits.to_s)
    increment_build_number(build_number: lane_context[SharedValues::LANE_NAME].split.last.capitalize)
    gym
  end

  lane :beta do |options|
    crashlytics(groups: ["Testers"])
  end

  lane :release do |options|
    crashlytics(groups: [ENV['APP_NAME']])
  end 

  lane :register do |options|
    register_devices(
      devices: {
        'Auto-Registered-Device' => options[:device]
      }
    )
  end 

  after_all do |lane|
    
  end

  error do |lane, exception|
    puts exception
    return if lane_context[SharedValues::LANE_NAME] == 'ios register'
    #raise 'Exit Jenkins'
  end
end
